Repository The-Balance-FFXIV/balance-static, pull requests merged in 2023-02, with the labels that each got.

#2156 Update Dancer guide “advanced-guide”
  content/jobs/ranged/dancer/advanced-guide.md
Labels: cms/pending_publish

#2164 Update Warrior guide “basic-guide”
  content/jobs/tanks/warrior/basic-guide.md
Labels: cms/pending_publish

#2162 Update Reaper guide “faq”
  content/jobs/melee/reaper/faq.md
Labels: cms/pending_publish

#2165 Update White Mage guide “bis”
  content/jobs/healers/white-mage/best-in-slot.md
Labels: cms/pending_publish

#2157 Update Dancer guide “job-changes”
  content/jobs/ranged/dancer/job-changes.md
Labels: cms/pending_publish

#2155 Update Dancer guide “faq”
  content/jobs/ranged/dancer/faq.md
Labels: cms/pending_publish

#2151 Update Dancer guide “leveling-guide”
  content/jobs/ranged/dancer/leveling-guide.md
Labels: cms/pending_publish

#2154 Update Dancer guide “openers”
  content/jobs/ranged/dancer/openers.md
Labels: cms/pending_publish

#2152 Update Dancer guide “basic-guide”
  content/jobs/ranged/dancer/basic-guide.md
Labels: cms/pending_publish

#2153 Update Dancer guide “skills-overview”
  content/jobs/ranged/dancer/skills-overview.md
Labels: cms/pending_publish

#2166 Create Dragoon Fight Tips “the-epic-of-alexander-ultimate-tea”
  content/jobs/melee/dragoon/fight-tips/the-epic-of-alexander-ultimate-tea.md
Labels: cms/pending_publish

#2167 Update White Mage guide “bis”
  content/jobs/healers/white-mage/best-in-slot.md
Labels: cms/pending_publish

#2168 Create Author profile “akashi”
  data/author/akashi.json
  static/img/profile/akashi.png
Labels: cms/pending_publish

#2169 Update Ninja guide “leveling-guide”
  content/jobs/melee/ninja/leveling-guide.md
Labels: cms/pending_publish

#2170 Update Dragoon Fight Tips “the-epic-of-alexander-ultimate-tea”
  content/jobs/melee/dragoon/fight-tips/the-epic-of-alexander-ultimate-tea.md
  static/img/drg_fight_tips.jpeg
Labels: cms/pending_review

#2150 Create Red Mage Fight Tips “abyssos”
  content/jobs/casters/red-mage/fight-tips/abyssos.md
  static/img/image2rdmp7s.png
  static/img/image4.png
  static/img/image5.png
  static/img/rotation240.png
  static/img/snakesnakecombined.png
Labels: cms/pending_publish

#2171 Update Author profile “shy”
  data/author/shy.json
Labels: cms/pending_review

#2175 Update Author profile “akashi”
  data/author/akashi.json
Labels: cms/draft

#2174 Update Ninja guide “leveling-guide”
  content/jobs/melee/ninja/leveling-guide.md
Labels: cms/pending_publish

#2177 Update Scholar guide “openers”
  content/jobs/healers/scholar/openers.md
Labels: cms/pending_publish

#2179 Update Machinist guide “bis”
  content/jobs/ranged/machinist/best-in-slot.md
Labels: cms/pending_publish

#2178 Update Ninja guide “bis”
  content/jobs/melee/ninja/best-in-slot.md
Labels: cms/pending_publish
